---
title: "R Notebook"
output: html_notebook
---

```{r}
start_time <- Sys.time()
set.seed(416)

library(mincombinr) # for displaying the resulting and loading the data
devtools::load_all() #loading gevitrec

#Table data
tab_dat<-input_data(file = system.file("./inst/extdata/", "ebov_metadata.csv", package = "gevitRec"),dataType = "table")

#Tree data
tree_dat<-input_data(file = system.file("./inst/extdata/", "ebov_tree.nwk", package = "gevitRec"),dataType = "tree")

#Genomic data
genomic_dat<-input_data(file = system.file("./inst/extdata/", "ebov_GIN_genomic.fasta", package = "gevitRec"),dataType = "dna")

#Shape files
#Shape files require that .shp,.shx,and .prj files at a minimun to be in the same directory
#to add metadata to the shape file, you can also add .dbf files
gin_shape_dat<-input_data(file = system.file("./inst/extdata/", "gin_admbnda_adm1_ocha_itos.shp", package = "gevitRec"),dataType = "spatial")
lbr_shape_dat<-input_data(file = system.file("./inst/extdata/", "lbr_admbnda_adm1_ocha.shp", package = "gevitRec"),dataType = "spatial")
sle_shape_dat<-input_data(file = system.file("extdata/", "sle_admbnda_adm1_1m_gov_ocha_20161017.shp",package = "gevitRec"),dataType = "spatial")
```


Modify the spatial objections to that they're more interesting to work with
```{r}
#join the spatial files
all_spatial<-join_spatial_data(gin_shape_dat,lbr_shape_dat,sle_shape_dat,obj_names = c("GIN","LBR","SLE"))
```

## Data Harmonization
```{r}
harmon_obj<-data_harmonization(tab_dat,tree_dat,genomic_dat,all_spatial)
view_entity_graph(harmon_obj[["entityGraph"]])
```


## Generate Specifications
```{r}
component_specs<-get_spec_list(harmon_obj)
```

## Look at the generated views

```{r}
plot_view(component_specs,view_num=1)
```

```{r}
plot_view(component_specs,view_num=2)
```

```{r}
plot_view(component_specs,view_num=3)
```

```{r}
plot_view(component_specs,view_num=4)
```

```{r}
plot_view(component_specs,view_num=5)
```
